name=input("Enter name : ")
age=input("Enter age : ")
gender=input("Enter gender : ")
dob=input("Enter DOB : ")
branch=input("Enter branch : ")
college=input("Enter college name : ")

print("PERSONAL DETAILS")
print("Name  :", name)
print("Age  :", age)
print("Gender  :", gender)
print("DOB  :", dob)
print("Branch  :", branch)
print("College  :", college)